"""add llm_cached and stage_timings_json to inference_runs

Revision ID: 0751f3a3997f
Revises: 85805a50b97f
Create Date: 2026-07-09 17:18:09.153691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0751f3a3997f'
down_revision: Union[str, Sequence[str], None] = '85805a50b97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Autogenerate produced NOT NULL columns with no server-side default,
    which fails on SQLite (and most DBs) as soon as `inference_runs` has any
    existing rows -- adjusted by hand to backfill them, matching the ORM's
    Python-side defaults (llm_cached=False, stage_timings_json={}).
    """
    op.add_column(
        'inference_runs',
        sa.Column('llm_cached', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'inference_runs',
        sa.Column('stage_timings_json', sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inference_runs', 'stage_timings_json')
    op.drop_column('inference_runs', 'llm_cached')
    # ### end Alembic commands ###
